steps: 
  - name: 'us-central1-docker.pkg.dev/project-1-sandbox-1223/docker-repo/terraform-cloudbuild-image:latest'
    id: init-terraform 
    entrypoint: /bin/bash
    dir: google_sandbox
    args: 
      - '-c'
      - set -x && terraform init && terraform validate
  - name: 'us-central1-docker.pkg.dev/project-1-sandbox-1223/docker-repo/terraform-cloudbuild-image:latest'
    id: plan-terraform
    entrypoint: /bin/bash
    dir: google_sandbox
    args: 
      - '-c'
      - >-
      set -x && terraform plan