steps:
  - name: gcr.io/cloud-builders/docker
    args: ['pull', 'hashicorp/terraform:latest']  

  - name: us-central1-docker.pkg.dev/project-1-sandbox-1223/docker-repo/terraform-cloudbuild-image  
    entrypoint: 'sh'
    args: ['-c', 'terraform init', 'terraform plan']

    