steps:
  - name: gcr.io/cloud-builders/docker
    args: ['pull', 'hashicorp/terraform:latest']  

  - name: us-central1-docker.pkg.dev/project-1-sandbox-1223/docker-repo/terraform-cloudbuild-image  
    entrypoint: 
      - 'usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    args: ['-c', 'terraform init', 'terraform plan']

    