steps:
- name: 'us-central1-docker.pkg.dev/project-1-sandbox-1223/docker-repo/terraform-cloudbuild-image:latest'
  id: pr
  entrypoint: /bin/bash
  args: 
  - '-c'
  - | 
    set -e
        terraform init
  
# - name: 'us-central1-docker.pkg.dev/project-1-sandbox-1223/docker-repo/terraform-cloudbuild-image:latest'
#   entrypoint: '/bin/bash/'
#   args: 
#   - '-c'
#   - | 
#     set -e
#         terraform plan
  
  
  
  
  
  
  
  
  
  # - name: gcr.io/cloud-builders/docker
  #   args: ['pull', 'hashicorp/terraform:latest']  

  # - name: us-central1-docker.pkg.dev/project-1-sandbox-1223/docker-repo/terraform-cloudbuild-image  
  #   entrypoint: '/bin/sh'
  #   args: ['-c', 'terraform init', 'terraform plan']

