steps:
  - name: 'hashicorp/terraform:latest'
    args:
      - '-c'
      - set -x && terraform init && terraform validate
    dir: google_sandbox
    id: init-terraform
    entrypoint: /bin/sh
  - name: 'hashicorp/terraform:latest'
    args:
      - '-c'
      - >-
        set -x && terraform plan
    dir: google_sandbox
    id: plan-terraform
    entrypoint: /bin/sh
timeout: 2000s
logsBucket: 'cloud-build-logs-6870'
options:
  logging: GCS_ONLY
tags:
  - pull-request